{
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/MDK_Demo_App_Clone/Actions/Service/SyncFailureMessage.action",
	"Service": "/MDK_Demo_App_Clone/Services/ServiceName.service",
	"DefiningRequests": [
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "Customers",
			"Query": "Customers"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "Products",
			"Query": "Products"
		},
		{
			"Name": "Stock",
			"Query": "Stock",
			"AutomaticallyRetrievesStreams": false
		}
	]
}