{
	"Animated": true,
	"CompletionMessage": "Sync Complete",
	"Message": "Upload in Process...",
	"OnFailure": "/MDK_Demo_App_Clone/Actions/Service/SyncFailureMessage.action",
	"OnSuccess": "/MDK_Demo_App_Clone/Actions/Service/UploadOffline.action",
	"_Type": "Action.Type.ProgressBanner"
}