{
	"_Type": "Action.Type.ODataService.DownloadMedia",
	"OnFailure": "/MDK_Demo_App_Clone/Actions/Initialize/GenericBannerMessage.action",
	"Target": {
		"EntitySet": "Products",
		"ReadLink": "{@odata.readLink}",
		"Service": "/MDK_Demo_App_Clone/Services/ServiceName.service"
	}
}